name: WindSpigot Build and Upload

on:
  push:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18.0.1
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 18.0.1
        server-id: github
        
    - name: Build with Maven
      run: mvn package --file pom.xml
      
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WindSpigot-server
        path: WindSpigot-Server/target/WindSpigot.jar

    - name: Upload API Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WindSpigot-API
        path: WindSpigot-API/target/WindSpigot-API.jar
